### ISSUE TITLE
Portal: prevent concurrent storeObject() on the same UOW

### ISSUE THREAD

**Issue by openmdx** [openmdx/openmdx#1]
Prevent exceptions of the form

`27-May-2020 09:14:22.807 WARNING [ajp-nio-8009-exec-19] org.openmdx.kernel.exception.Throwables.log Unit of work is active
 javax.jdo.JDOUserException: DefaultDomain.ILLEGAL_STATE
    BasicException[0]
	Class = org.openmdx.base.accessor.rest.UnitOfWork_1
	Method = begin
	Line = 641
	ExceptionClass = javax.jdo.JDOUserException
	ExceptionDomain = DefaultDomain
	ExceptionCode = ILLEGAL_STATE
	Description = Unit of work is active
	Timestamp = 2020-05-27T07:14:22.806Z
	StackTrace:
	    at org.openmdx.base.accessor.rest.UnitOfWork_1.begin(UnitOfWork_1.java:641)
	    at org.openmdx.base.accessor.spi.AbstractUnitOfWork_1.begin(AbstractUnitOfWork_1.java:145)
	    at org.openmdx.base.accessor.spi.AbstractUnitOfWork_1.begin(AbstractUnitOfWork_1.java:145)
	    at org.openmdx.base.accessor.spi.AbstractUnitOfWork_1.begin(AbstractUnitOfWork_1.java:145)
	    at org.openmdx.base.accessor.spi.AbstractUnitOfWork_1.begin(AbstractUnitOfWork_1.java:145)
	    at org.openmdx.application.persistence.adapter.TransactionAdapter.begin(TransactionAdapter.java:82)
	    at org.openmdx.portal.servlet.DefaultPortalExtension.storeObject(DefaultPortalExtension.java:2464)
	    at org.openmdx.portal.servlet.component.EditObjectView.storeObject(EditObjectView.java:413)
	    at org.openmdx.portal.servlet.action.SaveAction.perform(SaveAction.java:107)
	    at org.openmdx.portal.servlet.ObjectInspectorServlet.handleRequest(ObjectInspectorServlet.java:1193)
	    at org.openmdx.portal.servlet.ObjectInspectorServlet.doPost(ObjectInspectorServlet.java:1314)
	    at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
`

**Comment by openmdx** [comment]
fixed with openmdx-2.17-20200619
