### ISSUE TITLE
Portal: improve logging in case of non-accessible feature values

### ISSUE THREAD

**Issue by openmdx** [openmdx/openmdx#2]
Replace stack-trace at WARNING in case of non-accessible feature values with more informative information.

`BasicException[1]
Class = org.opencrx.kernel.layer.model.AccessControl_2$RestInteraction
Method = get
Line = 2006
ExceptionClass = javax.resource.ResourceException
ExceptionDomain = OpenCrxDomain
ExceptionCode = 1004
Description = No permission to access requested object.
Timestamp = 2020-06-19T05:36:57.170Z
Parameters:
    0:	object = xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/12345678
    1:	param0 = xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/12345678
    2:	param1 = Standard:guest
    3:	param2 = xri://@openmdx*org.openmdx.security.realm1/provider/CRX/segment/Root/realm/Standard/principal/guest.User
StackTrace:
    at org.opencrx.kernel.layer.model.AccessControl_2$RestInteraction.get(AccessControl_2.java:2006)
    at org.openmdx.base.rest.spi.AbstractRestInteraction.handleQuery(AbstractRestInteraction.java:488)
    at org.openmdx.base.rest.spi.AbstractRestInteraction.execute(AbstractRestInteraction.java:361)
    at org.openmdx.base.resource.spi.AbstractInteraction.execute(AbstractInteraction.java:247)
    at org.openmdx.base.rest.spi.AbstractRestInteraction.pass(AbstractRestInteraction.java:152)
    at org.openmdx.base.rest.spi.AbstractRestInteraction.get(AbstractRestInteraction.java:194)
    at org.opencrx.kernel.layer.application.OpenCrxKernel_2$RestInteraction.get(OpenCrxKernel_2.java:212)
    at org.openmdx.base.rest.spi.AbstractRestInteraction.handleQuery(AbstractRestInteraction.java:488)
    at org.openmdx.base.rest.spi.AbstractRestInteraction.execute(AbstractRestInteraction.java:361)
    at org.openmdx.base.resource.spi.AbstractInteraction.execute(AbstractInteraction.java:247)
    at org.openmdx.base.accessor.rest.spi.Switch_2$SwitchingInteraction.pass(Switch_2.java:230)
    at org.openmdx.base.rest.spi.AbstractRestInteraction.get(AbstractRestInteraction.java:194)
    at org.openmdx.base.rest.spi.AbstractRestInteraction.handleQuery(AbstractRestInteraction.java:488)
    at org.openmdx.base.rest.spi.AbstractRestInteraction.execute(AbstractRestInteraction.java:361)
    at org.openmdx.base.rest.spi.AbstractRestInteraction.execute(AbstractRestInteraction.java:577)
    at org.openmdx.application.rest.adapter.SuspendingConnectionAdapter$SuspendingInteractionAdapter.execute(SuspendingConnectionAdapter.java:430)
    at org.openmdx.application.rest.adapter.SuspendingConnectionAdapter$SuspendingInteractionAdapter.execute(SuspendingConnectionAdapter.java:478)
    at org.openmdx.base.accessor.rest.DataObject_1.unconditionalLoad(DataObject_1.java:902)
    at org.openmdx.base.accessor.rest.DataObject_1.objRetrieve(DataObject_1.java:2719)
    at org.openmdx.base.accessor.rest.DataObject_1.objGetClass(DataObject_1.java:729)
    at org.openmdx.base.aop1.PlugIn_1.getInterceptor(PlugIn_1.java:131)`

**Comment by openmdx** [comment]
fixed with openmdx-2.17.0+
